### ISSUE TITLE
Add some new team mates

### ISSUE THREAD

**Issue by smc204** [smc204/friendly-collab-repo#5]
I'm keen to add a list of departments represented at the beginners course. Can you add a file with your department to my repository?

**Comment by rollerlibrarian** [comment]
Sure! I can do this. Do you want me to add my department name to an existing file in your repo?

**Comment by villadsegede** [comment]
I also think adding all users to an existing file would be easier

**Comment by smc204** [comment]
I'm quite keen to see how new files are added. Can you add a new file for me with the start of a list?

**Comment by rollerlibrarian** [comment]
How's this?
[GitHub departments.txt](https://github.com/smc204/friendly-collab-repo/files/704633/GitHub.departments.txt)

**Comment by smc204** [comment]
Thanks all!
